export const CURRENCIES_CLEAN = 'CURRENCIES_CLEAN';
export const CURRENCIES_FAIL = 'CURRENCIES_FAIL';
export const CURRENCIES_GET_LIST_SUCCESS = 'CURRENCIES_GET_LIST_SUCCESS';
export const CURRENCIES_RESET_ERROR = 'CURRENCIES_RESET_ERROR';
export const CURRENCIES_START = 'CURRENCIES_START';

export const ENV_LOAD = 'ENV_LOAD';

export const PRODUCTS_CLEAN = 'PRODUCTS_CLEAN';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const PRODUCTS_GET_LIST_SUCCESS = 'PRODUCTS_GET_LIST_SUCCESS';
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_RESET_ERROR = 'PRODUCTS_RESET_ERROR';
export const PRODUCTS_RESET_SELECTED = 'PRODUCTS_RESET_SELECTED';
export const PRODUCTS_START = 'PRODUCTS_START';